#services:
#  database:
#    image: mysql:8.0
#    container_name: febank-mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: febank
#    healthcheck:
#      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
#      interval: 5s
#      timeout: 5s
#      retries: 10
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#  app:
#    build: .
#    volumes:
#      - .:/app
#    container_name: febank-app
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/febank
#      - SPRING_DATASOURCE_USERNAME=root
#      - SPRING_DATASOURCE_PASSWORD=root
#    ports:
#      - "8080:8080"
#    depends_on:
#      database:
#        condition: service_healthy
#
#volumes:
#  mysql_data: